# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module MaterialCost
      class DeleteWorkOrderCosts < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[MaterialCostIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
