# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module State
      class Update < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[StateCode].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
