# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Holidays
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Description Holiday].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
