# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Holidays
      class ByDate < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Date].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
