# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Holidays
      class Delete < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Holidays].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
