# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module EquipmentReservation
      class DeleteReservation < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[TransactionIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
