# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module EquipmentReservation
      class Status < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EquipmentSids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
