# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module UniversalCustomField
      class Delete < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[FieldIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
