# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module PeopleRole
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[RoleCode].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
