# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Equipment
      class ById < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EquipmentSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
