# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module PavementInspection
      class Distresses < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[SampleId SampleIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
