# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module LaborCost
      class AddWorkOrderCosts < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Hours WorkOrderId WorkOrderSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
