# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module LaborCost
      class InspectionCostsByInspection < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[InspectionIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
