# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module ServiceRequest
      class Combine < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[FromRequestIds ToRequestId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
