# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Entity
      class FiveNumberSummary < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Attribute EntityType].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
