# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Entity
      class GroupByType < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntityType].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
