# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Crew
      class ByEmployee < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
