# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Security
      class InspectionTemplates < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[InspTemplateIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
