# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Projects
      class AddEntities < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntityType EntityUids ProjectSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
