# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Projects
      class RemoveEntities < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Ids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
