# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module TemplateMapLayer
      class DeleteInspectionInstancesByInspectionId < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[InspectionId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
