# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module TemplateMapLayer
      class UpdateServiceRequestInstanceMapLayers < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[DomainId ServiceRequestId X Y].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
