# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module TemplateMapLayer
      class WorkOrderInstanceMapLayersByWorkOrderId < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[WorkOrderId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
