# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Bookmark
      class UpdateScale < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ScaleId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
