# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module ScheduleEvent
      class ByEmployeeSids < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EmployeeSids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
