# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module ScheduleEvent
      class ByIds < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ScheduleEventIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
