# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module ActivityNotification
      class UserWatching < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ActivityId ActivityType].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
