# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Inspection
      class CreateFromEntities < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntityType InspTemplateId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
