# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseInstReleases
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[AmountReleased CaInstrumentId DateReleased PercentReleased ReleasedBy].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
