# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module ActivityLink
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[DestSid DestType LinkType SourceSid SourceType].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
