# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Authentication
      class Validate < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Token].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
