# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseObject
      class Move < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[caObjectId X Y].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
