# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseDataGroup
      class UpdateFromAsset < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaObjectId EntityType EntityUid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
