# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module EquipmentChangeOut
      class DeleteOperations < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[OperationIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
