# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module EquipmentChangeOut
      class DirectParent < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntitySid EntityType EntityUid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
