# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module EquipmentChangeOut
      class Entities < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntitySids EntityType EntityUids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
