# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Contract
      class AddInvoiceItem < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[InvoiceId LineItemCostId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
