# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Contract
      class UpdateFundSource < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[FundSourceId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
