# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Authorization
      class LicensedApiCheck < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Area Service].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
