# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Authorization
      class LicensedFeatureCheck < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Feature].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
