# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Authorization
      class LicensedExtensionsCheck < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Extensions].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
