# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Gis
    module MapService
      class WorkOrderConfiguration < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
