# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module CwMetaData
      class ByTableNameSids < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Ids TableName].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
