# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseCondition
      class SearchObject < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
