# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseFeesDataGroup
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaDataGroupId CaFeeId Sequence].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
