# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Reading
      class ByEntity < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntityId EntityType ReadingName].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
