# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module CustomerCall
      class AddToRequest < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[RequestId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
