# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module CustomerCall
      class ByRequestIds < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[RequestIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
