# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Condition
      class History < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntityType EntityUids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
