# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Contractor
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ContractorName].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
