# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module Query
      class QueryTypes < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
