# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Designer
      class AddAttachmentMapping < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Source].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
