# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Designer
      class CreateUser < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Email EmployeeSid Password].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
