# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Designer
      class UpdateCodeType < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CodeType Description Module].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
