# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseReceipt
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[LoginId OrgId ReceiptDate ReceiptFileName TotalAmountDue TotalAmountTendered UserId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
