# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseFlags
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[AppliedBy CaObjectId DateApplied FlagId Severity].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
