# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CasePayment
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaFeeId CaObjectId CustFeeSeq DateReceived PaymentAmount PaymentDate ReceivedBy TenderTypeId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
