# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CasePayment
      class AddDeposit < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaDepositId CaObjectId DateReceived PaymentAmount PaymentDate ReceivedBy TenderTypeId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
