# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module WorkOrderEntity
      class ByWorkOrderSids < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[WorkOrderSids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
