# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module WorkOrder
      class CreateFromParent < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntityType WorkOrderId WorkOrderSid WOTemplateId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
