# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module WorkOrder
      class Create < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EntityType WOTemplateId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
