# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseFees
      class Delete < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaFeeId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
