# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Permit
      class DeletePermits < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[PermitSids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
