# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Permit
      class UpdatePermit < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[PermitSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
