# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseAddress
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaObjectId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
