# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module WorkOrderTemplate
      class ByTemplateClassIds < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[TemplateClassIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
