# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module Case
      class GetDefaultItemsList < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaseTypeId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
