# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module Case
      class GetDefaultItems < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = [].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
