# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Storeroom
      class AddRequisitionItem < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[MaterialSid QtyInPkg Quantity RequisitionSid SupplierSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
