# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Storeroom
      class AddReceive < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Destination MaterialSid Quantity].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
