# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Storeroom
      class RequisitionItems < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[RequisitionSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
