# AUTOGENERATED DO NOT EDIT

module Cityworks
  module General
    module PavementManagementInterface
      class ProcessRecommendedWorkCsvFile < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Data Delimiter].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
