# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Tasks
      class ById < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[WOTaskId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
