# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module GISService
      class AddGISServiceEndPointSecurity < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Service ServiceName].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
