# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module GISService
      class ValidateServiceSecurity < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[SecurityIds].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
