# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Inbox
      class CreateWidgetZone < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ContainerId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
