# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module TvInspection
      class ConfirmSmokeTests < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[TvId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
