# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseViolations
      class CompleteViolations < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaViolationId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
