# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Employee
      class ByGroupId < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[GroupId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
