# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Employee
      class CustomDataFields < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[EmployeeSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
