# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Attachments
      class AddWorkOrderAttachment < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[WorkOrderId WorkOrderSid].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
