# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Attachments
      class AddTvObservationAttachment < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ObservationId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
