# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Attachments
      class AddInspectionAttachment < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[InspectionId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
