# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Comment
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ActivityType Comments].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
