# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Comment
      class ByActivityTypes < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ActivityTypes].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
