# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module Comment
      class ProblemComments < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[ProblemSids].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
