# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseDataDetail
      class UpdateLock < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaDataDetailId Lock].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
