# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module ManholeInspection
      class ByWorkOrders < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
