# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Ams
    module ManholeInspection
      class UpdateObservation < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[MhObservId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
