# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseInstrument
      class Add < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[Amount CaObjectId DateExpire InstTypeId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
