# AUTOGENERATED DO NOT EDIT

module Cityworks
  module Pll
    module CaseInstrument
      class ByCaObjectId < ::Cityworks::BaseServiceRequest
        class Parameters < ::Cityworks::RequestParameters
          REQUIRED = %w[CaObjectId].freeze
        end

        class Response < ::Cityworks::BaseResponse
        end
      end
    end
  end
end
